const WAITING_FOR_PLAYERS =
  'WAITING_FOR_PLAYER';
const SUGGESTING_CHARACTERS =
  'SUGGESTING_CHARACTER';
const PROCESSING_QUESTION =
  'PROCESSING_QUESTION';
const NUMBER_OF_PLAYERS = 4;
const READY = 'READY';
const NOT_READY = 'NOT_READY';
const ASKING = 'ASKING';
const ANSWERING = 'ANSWERING';
const FINISHED = 'FINISHED';
const YES = 'YES';
const NO = 'NO';
const NOT_SURE = 'NOT_SURE';

export {
  WAITING_FOR_PLAYERS,
  SUGGESTING_CHARACTERS,
  PROCESSING_QUESTION,
  NUMBER_OF_PLAYERS,
  READY,
  NOT_READY,
  ASKING,
  ANSWERING,
  FINISHED,
  YES,
  NO,
  NOT_SURE,
};
